export const dataTeam = [
  {
    team: {
      code: "MUN",
      country: "England",
      founded: 1878,
      id: 33,
      logo: "https://media-3.api-sports.io/football/teams/33.png",
      name: "Manchester United",
      national: false,
    },
    venue: {
      address: "Sir Matt Busby Way",
      capacity: 76212,
      city: "Manchester",
      id: 556,
      image: "https://media.api-sports.io/football/venues/556.png",
      name: "Old Trafford",
      surface: "grass",
    },
  },
  {
    team: {
      code: "NEW",
      country: "England",
      founded: 1892,
      id: 34,
      logo: "https://media-3.api-sports.io/football/teams/34.png",
      name: "Newcastle",
      national: false,
    },
    venue: {
      address: "St. James&apos; Street",
      capacity: 52389,
      city: "Newcastle upon Tyne",
      id: 562,
      image: "https://media.api-sports.io/football/venues/562.png",
      name: "St. James' Park",
      surface: "grass",
    },
  },
  {
    team: {
      code: "BOU",
      country: "England",
      founded: 1899,
      id: 35,
      logo: "https://media.api-sports.io/football/teams/35.png",
      name: "Bournemouth",
      national: false,
    },
    venue: {
      address: "Dean Court, Kings Park",
      capacity: 12000,
      city: "Bournemouth, Dorset",
      id: 504,
      image: "https://media-3.api-sports.io/football/venues/504.png",
      name: "Vitality Stadium",
      surface: "grass",
    },
  },
  {
    team: {
      code: "FUL",
      country: "England",
      founded: 1879,
      id: 36,
      logo: "https://media-3.api-sports.io/football/teams/36.png",
      name: "Fulham",
      national: false,
    },
    venue: {
      address: "Stevenage Road",
      capacity: 25700,
      city: "London",
      id: 535,
      image: "https://media-3.api-sports.io/football/venues/535.png",
      name: "Craven Cottage",
      surface: "grass",
    },
  },
  {
    team: {
      code: "WOL",
      country: "England",
      founded: 1877,
      id: 39,
      logo: "https://media.api-sports.io/football/teams/39.png",
      name: "Wolves",
      national: false,
    },
    venue: {
      id: 600,
      name: "Molineux Stadium",
      address: "Waterloo Road",
      city: "Wolverhampton, West Midlands",
      capacity: 32050,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/600.png",
    },
  },
  {
    team: {
      id: 40,
      name: "Liverpool",
      code: "LIV",
      country: "England",
      founded: 1892,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/40.png",
    },
    venue: {
      id: 550,
      name: "Anfield",
      address: "Anfield Road",
      city: "Liverpool",
      capacity: 55212,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/550.png",
    },
  },
  {
    team: {
      id: 41,
      name: "Southampton",
      code: "SOU",
      country: "England",
      founded: 1885,
      national: false,
      logo: "https://media.api-sports.io/football/teams/41.png",
    },
    venue: {
      id: 585,
      name: "St. Mary's Stadium",
      address: "Britannia Road",
      city: "Southampton, Hampshire",
      capacity: 32689,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/585.png",
    },
  },
  {
    team: {
      id: 42,
      name: "Arsenal",
      code: "ARS",
      country: "England",
      founded: 1886,
      national: false,
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    venue: {
      id: 494,
      name: "Emirates Stadium",
      address: "Queensland Road",
      city: "London",
      capacity: 60383,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/494.png",
    },
  },
  {
    team: {
      id: 45,
      name: "Everton",
      code: "EVE",
      country: "England",
      founded: 1878,
      national: false,
      logo: "https://media.api-sports.io/football/teams/45.png",
    },
    venue: {
      id: 8560,
      name: "Goodison Park",
      address: "Goodison Road",
      city: "Liverpool",
      capacity: 40569,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/8560.png",
    },
  },
  {
    team: {
      id: 46,
      name: "Leicester",
      code: "LEI",
      country: "England",
      founded: 1884,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/46.png",
    },
    venue: {
      id: 547,
      name: "King Power Stadium",
      address: "Filbert Way",
      city: "Leicester, Leicestershire",
      capacity: 34310,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/547.png",
    },
  },
  {
    team: {
      id: 47,
      name: "Tottenham",
      code: "TOT",
      country: "England",
      founded: 1882,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/47.png",
    },
    venue: {
      id: 593,
      name: "Tottenham Hotspur Stadium",
      address: "Bill Nicholson Way, 748 High Road",
      city: "London",
      capacity: 62850,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/593.png",
    },
  },
  {
    team: {
      id: 48,
      name: "West Ham",
      code: "WES",
      country: "England",
      founded: 1895,
      national: false,
      logo: "https://media.api-sports.io/football/teams/48.png",
    },
    venue: {
      id: 598,
      name: "London Stadium",
      address: "Marshgate Lane, Stratford",
      city: "London",
      capacity: 62500,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/598.png",
    },
  },
  {
    team: {
      id: 49,
      name: "Chelsea",
      code: "CHE",
      country: "England",
      founded: 1905,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/49.png",
    },
    venue: {
      id: 519,
      name: "Stamford Bridge",
      address: "Fulham Road",
      city: "London",
      capacity: 41841,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/519.png",
    },
  },
  {
    team: {
      id: 50,
      name: "Manchester City",
      code: "MAC",
      country: "England",
      founded: 1880,
      national: false,
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    venue: {
      id: 555,
      name: "Etihad Stadium",
      address: "Rowsley Street",
      city: "Manchester",
      capacity: 55097,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/555.png",
    },
  },
  {
    team: {
      id: 51,
      name: "Brighton",
      code: "BRI",
      country: "England",
      founded: 1901,
      national: false,
      logo: "https://media.api-sports.io/football/teams/51.png",
    },
    venue: {
      id: 508,
      name: "The American Express Community Stadium",
      address: "Village Way",
      city: "Falmer, East Sussex",
      capacity: 31800,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/508.png",
    },
  },
  {
    team: {
      id: 52,
      name: "Crystal Palace",
      code: "CRY",
      country: "England",
      founded: 1905,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/52.png",
    },
    venue: {
      id: 525,
      name: "Selhurst Park",
      address: "Holmesdale Road",
      city: "London",
      capacity: 26309,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/525.png",
    },
  },
  {
    team: {
      id: 55,
      name: "Brentford",
      code: "BRE",
      country: "England",
      founded: 1889,
      national: false,
      logo: "https://media.api-sports.io/football/teams/55.png",
    },
    venue: {
      id: 10503,
      name: "Gtech Community Stadium",
      address: "166 Lionel Rd N, Brentford",
      city: "Brentford, Middlesex",
      capacity: 17250,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/10503.png",
    },
  },
  {
    team: {
      id: 63,
      name: "Leeds",
      code: "LEE",
      country: "England",
      founded: 1919,
      national: false,
      logo: "https://media.api-sports.io/football/teams/63.png",
    },
    venue: {
      id: 546,
      name: "Elland Road",
      address: "Elland Road",
      city: "Leeds, West Yorkshire",
      capacity: 40204,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/546.png",
    },
  },
  {
    team: {
      id: 65,
      name: "Nottingham Forest",
      code: "NOT",
      country: "England",
      founded: 1865,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/65.png",
    },
    venue: {
      id: 566,
      name: "The City Ground",
      address: "Pavilion Road",
      city: "Nottingham, Nottinghamshire",
      capacity: 30576,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/566.png",
    },
  },
  {
    team: {
      id: 66,
      name: "Aston Villa",
      code: "AST",
      country: "England",
      founded: 1874,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/66.png",
    },
    venue: {
      id: 495,
      name: "Villa Park",
      address: "Trinity Road",
      city: "Birmingham",
      capacity: 42788,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/495.png",
    },
  },
];

export const league = [
  {
    id: 39,
    name: "Premier League",
    type: "League",
    logo: "https://media-3.api-sports.io/football/leagues/39.png",
  },
  {
    id: 78,
    name: "Bundesliga",
    type: "League",
    logo: "https://media-3.api-sports.io/football/leagues/78.png",
  },
  {
    id: 135,
    name: "Serie A",
    type: "League",
    logo: "https://media.api-sports.io/football/leagues/135.png",
  },
];
