export const dataTeam = [
  {
    team: {
      code: "MUN",
      country: "England",
      founded: 1878,
      id: 33,
      logo: "https://media-3.api-sports.io/football/teams/33.png",
      name: "Manchester United",
      national: false,
    },
    venue: {
      address: "Sir Matt Busby Way",
      capacity: 76212,
      city: "Manchester",
      id: 556,
      image: "https://media.api-sports.io/football/venues/556.png",
      name: "Old Trafford",
      surface: "grass",
    },
  },
  {
    team: {
      code: "NEW",
      country: "England",
      founded: 1892,
      id: 34,
      logo: "https://media-3.api-sports.io/football/teams/34.png",
      name: "Newcastle",
      national: false,
    },
    venue: {
      address: "St. James&apos; Street",
      capacity: 52389,
      city: "Newcastle upon Tyne",
      id: 562,
      image: "https://media.api-sports.io/football/venues/562.png",
      name: "St. James' Park",
      surface: "grass",
    },
  },
  {
    team: {
      code: "BOU",
      country: "England",
      founded: 1899,
      id: 35,
      logo: "https://media.api-sports.io/football/teams/35.png",
      name: "Bournemouth",
      national: false,
    },
    venue: {
      address: "Dean Court, Kings Park",
      capacity: 12000,
      city: "Bournemouth, Dorset",
      id: 504,
      image: "https://media-3.api-sports.io/football/venues/504.png",
      name: "Vitality Stadium",
      surface: "grass",
    },
  },
  {
    team: {
      code: "FUL",
      country: "England",
      founded: 1879,
      id: 36,
      logo: "https://media-3.api-sports.io/football/teams/36.png",
      name: "Fulham",
      national: false,
    },
    venue: {
      address: "Stevenage Road",
      capacity: 25700,
      city: "London",
      id: 535,
      image: "https://media-3.api-sports.io/football/venues/535.png",
      name: "Craven Cottage",
      surface: "grass",
    },
  },
  {
    team: {
      code: "WOL",
      country: "England",
      founded: 1877,
      id: 39,
      logo: "https://media.api-sports.io/football/teams/39.png",
      name: "Wolves",
      national: false,
    },
    venue: {
      id: 600,
      name: "Molineux Stadium",
      address: "Waterloo Road",
      city: "Wolverhampton, West Midlands",
      capacity: 32050,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/600.png",
    },
  },
  {
    team: {
      id: 40,
      name: "Liverpool",
      code: "LIV",
      country: "England",
      founded: 1892,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/40.png",
    },
    venue: {
      id: 550,
      name: "Anfield",
      address: "Anfield Road",
      city: "Liverpool",
      capacity: 55212,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/550.png",
    },
  },
  {
    team: {
      id: 41,
      name: "Southampton",
      code: "SOU",
      country: "England",
      founded: 1885,
      national: false,
      logo: "https://media.api-sports.io/football/teams/41.png",
    },
    venue: {
      id: 585,
      name: "St. Mary's Stadium",
      address: "Britannia Road",
      city: "Southampton, Hampshire",
      capacity: 32689,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/585.png",
    },
  },
  {
    team: {
      id: 42,
      name: "Arsenal",
      code: "ARS",
      country: "England",
      founded: 1886,
      national: false,
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    venue: {
      id: 494,
      name: "Emirates Stadium",
      address: "Queensland Road",
      city: "London",
      capacity: 60383,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/494.png",
    },
  },
  {
    team: {
      id: 45,
      name: "Everton",
      code: "EVE",
      country: "England",
      founded: 1878,
      national: false,
      logo: "https://media.api-sports.io/football/teams/45.png",
    },
    venue: {
      id: 8560,
      name: "Goodison Park",
      address: "Goodison Road",
      city: "Liverpool",
      capacity: 40569,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/8560.png",
    },
  },
  {
    team: {
      id: 46,
      name: "Leicester",
      code: "LEI",
      country: "England",
      founded: 1884,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/46.png",
    },
    venue: {
      id: 547,
      name: "King Power Stadium",
      address: "Filbert Way",
      city: "Leicester, Leicestershire",
      capacity: 34310,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/547.png",
    },
  },
  {
    team: {
      id: 47,
      name: "Tottenham",
      code: "TOT",
      country: "England",
      founded: 1882,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/47.png",
    },
    venue: {
      id: 593,
      name: "Tottenham Hotspur Stadium",
      address: "Bill Nicholson Way, 748 High Road",
      city: "London",
      capacity: 62850,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/593.png",
    },
  },
  {
    team: {
      id: 48,
      name: "West Ham",
      code: "WES",
      country: "England",
      founded: 1895,
      national: false,
      logo: "https://media.api-sports.io/football/teams/48.png",
    },
    venue: {
      id: 598,
      name: "London Stadium",
      address: "Marshgate Lane, Stratford",
      city: "London",
      capacity: 62500,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/598.png",
    },
  },
  {
    team: {
      id: 49,
      name: "Chelsea",
      code: "CHE",
      country: "England",
      founded: 1905,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/49.png",
    },
    venue: {
      id: 519,
      name: "Stamford Bridge",
      address: "Fulham Road",
      city: "London",
      capacity: 41841,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/519.png",
    },
  },
  {
    team: {
      id: 50,
      name: "Manchester City",
      code: "MAC",
      country: "England",
      founded: 1880,
      national: false,
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    venue: {
      id: 555,
      name: "Etihad Stadium",
      address: "Rowsley Street",
      city: "Manchester",
      capacity: 55097,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/555.png",
    },
  },
  {
    team: {
      id: 51,
      name: "Brighton",
      code: "BRI",
      country: "England",
      founded: 1901,
      national: false,
      logo: "https://media.api-sports.io/football/teams/51.png",
    },
    venue: {
      id: 508,
      name: "The American Express Community Stadium",
      address: "Village Way",
      city: "Falmer, East Sussex",
      capacity: 31800,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/508.png",
    },
  },
  {
    team: {
      id: 52,
      name: "Crystal Palace",
      code: "CRY",
      country: "England",
      founded: 1905,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/52.png",
    },
    venue: {
      id: 525,
      name: "Selhurst Park",
      address: "Holmesdale Road",
      city: "London",
      capacity: 26309,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/525.png",
    },
  },
  {
    team: {
      id: 55,
      name: "Brentford",
      code: "BRE",
      country: "England",
      founded: 1889,
      national: false,
      logo: "https://media.api-sports.io/football/teams/55.png",
    },
    venue: {
      id: 10503,
      name: "Gtech Community Stadium",
      address: "166 Lionel Rd N, Brentford",
      city: "Brentford, Middlesex",
      capacity: 17250,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/10503.png",
    },
  },
  {
    team: {
      id: 63,
      name: "Leeds",
      code: "LEE",
      country: "England",
      founded: 1919,
      national: false,
      logo: "https://media.api-sports.io/football/teams/63.png",
    },
    venue: {
      id: 546,
      name: "Elland Road",
      address: "Elland Road",
      city: "Leeds, West Yorkshire",
      capacity: 40204,
      surface: "grass",
      image: "https://media.api-sports.io/football/venues/546.png",
    },
  },
  {
    team: {
      id: 65,
      name: "Nottingham Forest",
      code: "NOT",
      country: "England",
      founded: 1865,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/65.png",
    },
    venue: {
      id: 566,
      name: "The City Ground",
      address: "Pavilion Road",
      city: "Nottingham, Nottinghamshire",
      capacity: 30576,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/566.png",
    },
  },
  {
    team: {
      id: 66,
      name: "Aston Villa",
      code: "AST",
      country: "England",
      founded: 1874,
      national: false,
      logo: "https://media-3.api-sports.io/football/teams/66.png",
    },
    venue: {
      id: 495,
      name: "Villa Park",
      address: "Trinity Road",
      city: "Birmingham",
      capacity: 42788,
      surface: "grass",
      image: "https://media-3.api-sports.io/football/venues/495.png",
    },
  },
];

export const league = [
  {
    id: 39,
    name: "Premier League",
    type: "League",
    logo: "https://media-3.api-sports.io/football/leagues/39.png",
  },
  {
    id: 78,
    name: "Bundesliga",
    type: "League",
    logo: "https://media-3.api-sports.io/football/leagues/78.png",
  },
  {
    id: 135,
    name: "Serie A",
    type: "League",
    logo: "https://media.api-sports.io/football/leagues/135.png",
  },
];

export const team = {
  league: {
    id: 39,
    name: "Premier League",
    country: "England",
    logo: "https://media.api-sports.io/football/leagues/39.png",
    flag: "https://media-3.api-sports.io/flags/gb.svg",
    season: 2022,
  },
  team: {
    id: 41,
    name: "Southampton",
    logo: "https://media-3.api-sports.io/football/teams/41.png",
  },
  form: "LDWLWLLLLDWDLLLLLDWLWLLLLDWDLLLLDWDLLLL",
  fixtures: {
    played: { home: 10, away: 11, total: 21 },
    wins: { home: 1, away: 3, total: 4 },
    draws: { home: 3, away: 0, total: 3 },
    loses: { home: 6, away: 8, total: 14 },
  },
  goals: {
    for: {
      total: { home: 9, away: 8, total: 17 },
      average: { home: "0.9", away: "0.7", total: "0.8" },
      minute: {
        "0-15": { total: 3, percentage: "15.00%" },
        "16-30": { total: 2, percentage: "10.00%" },
        "31-45": { total: 2, percentage: "10.00%" },
        "46-60": { total: 4, percentage: "20.00%" },
        "61-75": { total: 5, percentage: "25.00%" },
        "76-90": { total: 4, percentage: "20.00%" },
        "91-105": { total: null, percentage: null },
        "106-120": { total: null, percentage: null },
      },
    },
    against: {
      total: { home: 17, away: 21, total: 38 },
      average: { home: "1.7", away: "1.9", total: "1.8" },
      minute: {
        "0-15": { total: 3, percentage: "8.57%" },
        "16-30": { total: 5, percentage: "14.29%" },
        "31-45": { total: 9, percentage: "25.71%" },
        "46-60": { total: 10, percentage: "28.57%" },
        "61-75": { total: 4, percentage: "11.43%" },
        "76-90": { total: 3, percentage: "8.57%" },
        "91-105": { total: 1, percentage: "2.86%" },
        "106-120": { total: null, percentage: null },
      },
    },
  },
  biggest: {
    streak: { wins: 1, draws: 1, loses: 6 },
    wins: { home: "2-1", away: "1-2" },
    loses: { home: "1-4", away: "4-0" },
    goals: { for: { home: 2, away: 2 }, against: { home: 4, away: 4 } },
  },
  clean_sheet: { home: 0, away: 1, total: 1 },
  failed_to_score: { home: 3, away: 5, total: 8 },
  penalty: {
    scored: { total: 0, percentage: "0%" },
    missed: { total: 0, percentage: "0%" },
    total: 0,
  },
  lineups: [
    { formation: "4-2-3-1", played: 9 },
    { formation: "4-4-2", played: 5 },
    { formation: "5-3-2", played: 2 },
    { formation: "3-4-2-1", played: 2 },
    { formation: "4-3-3", played: 1 },
    { formation: "3-1-4-2", played: 1 },
    { formation: "3-4-1-2", played: 1 },
  ],
  cards: {
    yellow: {
      "0-15": { total: 5, percentage: "14.71%" },
      "16-30": { total: 1, percentage: "2.94%" },
      "31-45": { total: 7, percentage: "20.59%" },
      "46-60": { total: 3, percentage: "8.82%" },
      "61-75": { total: 6, percentage: "17.65%" },
      "76-90": { total: 7, percentage: "20.59%" },
      "91-105": { total: 5, percentage: "14.71%" },
      "106-120": { total: null, percentage: null },
    },
    red: {
      "0-15": { total: null, percentage: null },
      "16-30": { total: null, percentage: null },
      "31-45": { total: null, percentage: null },
      "46-60": { total: null, percentage: null },
      "61-75": { total: null, percentage: null },
      "76-90": { total: null, percentage: null },
      "91-105": { total: null, percentage: null },
      "106-120": { total: null, percentage: null },
    },
  },
};

export const standing = [
  {
    league: {
      id: 39,
      name: "Premier League",
      country: "England",
      logo: "https://media.api-sports.io/football/leagues/39.png",
      flag: "https://media-3.api-sports.io/flags/gb.svg",
      season: 2022,
      standings: [
        [
          {
            rank: 1,
            team: {
              id: 42,
              name: "Arsenal",
              logo: "https://media.api-sports.io/football/teams/42.png",
            },
            points: 51,
            goalsDiff: 28,
            group: "Premier League",
            form: "DLWWD",
            status: "same",
            description: "Promotion - Champions League (Group Stage)",
            all: {
              played: 21,
              win: 16,
              draw: 3,
              lose: 2,
              goals: { for: 46, against: 18 },
            },
            home: {
              played: 10,
              win: 8,
              draw: 2,
              lose: 0,
              goals: { for: 26, against: 11 },
            },
            away: {
              played: 11,
              win: 8,
              draw: 1,
              lose: 2,
              goals: { for: 20, against: 7 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 2,
            team: {
              id: 50,
              name: "Manchester City",
              logo: "https://media-3.api-sports.io/football/teams/50.png",
            },
            points: 45,
            goalsDiff: 32,
            group: "Premier League",
            form: "LWWLW",
            status: "same",
            description: "Promotion - Champions League (Group Stage)",
            all: {
              played: 21,
              win: 14,
              draw: 3,
              lose: 4,
              goals: { for: 53, against: 21 },
            },
            home: {
              played: 11,
              win: 9,
              draw: 1,
              lose: 1,
              goals: { for: 38, against: 12 },
            },
            away: {
              played: 10,
              win: 5,
              draw: 2,
              lose: 3,
              goals: { for: 15, against: 9 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 3,
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media.api-sports.io/football/teams/33.png",
            },
            points: 43,
            goalsDiff: 8,
            group: "Premier League",
            form: "DWLDW",
            status: "same",
            description: "Promotion - Champions League (Group Stage)",
            all: {
              played: 22,
              win: 13,
              draw: 4,
              lose: 5,
              goals: { for: 36, against: 28 },
            },
            home: {
              played: 11,
              win: 8,
              draw: 2,
              lose: 1,
              goals: { for: 21, against: 8 },
            },
            away: {
              played: 11,
              win: 5,
              draw: 2,
              lose: 4,
              goals: { for: 15, against: 20 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 4,
            team: {
              id: 34,
              name: "Newcastle",
              logo: "https://media.api-sports.io/football/teams/34.png",
            },
            points: 41,
            goalsDiff: 22,
            group: "Premier League",
            form: "DDDWD",
            status: "same",
            description: "Promotion - Champions League (Group Stage)",
            all: {
              played: 22,
              win: 10,
              draw: 11,
              lose: 1,
              goals: { for: 35, against: 13 },
            },
            home: {
              played: 11,
              win: 6,
              draw: 5,
              lose: 0,
              goals: { for: 19, against: 6 },
            },
            away: {
              played: 11,
              win: 4,
              draw: 6,
              lose: 1,
              goals: { for: 16, against: 7 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 5,
            team: {
              id: 47,
              name: "Tottenham",
              logo: "https://media-3.api-sports.io/football/teams/47.png",
            },
            points: 39,
            goalsDiff: 7,
            group: "Premier League",
            form: "LWWLL",
            status: "same",
            description: "Promotion - Europa League (Group Stage)",
            all: {
              played: 23,
              win: 12,
              draw: 3,
              lose: 8,
              goals: { for: 42, against: 35 },
            },
            home: {
              played: 11,
              win: 7,
              draw: 0,
              lose: 4,
              goals: { for: 22, against: 15 },
            },
            away: {
              played: 12,
              win: 5,
              draw: 3,
              lose: 4,
              goals: { for: 20, against: 20 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 6,
            team: {
              id: 51,
              name: "Brighton",
              logo: "https://media-3.api-sports.io/football/teams/51.png",
            },
            points: 35,
            goalsDiff: 11,
            group: "Premier League",
            form: "DWDWW",
            status: "same",
            description: null,
            all: {
              played: 21,
              win: 10,
              draw: 5,
              lose: 6,
              goals: { for: 39, against: 28 },
            },
            home: {
              played: 10,
              win: 5,
              draw: 2,
              lose: 3,
              goals: { for: 17, against: 10 },
            },
            away: {
              played: 11,
              win: 5,
              draw: 3,
              lose: 3,
              goals: { for: 22, against: 18 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 7,
            team: {
              id: 36,
              name: "Fulham",
              logo: "https://media.api-sports.io/football/teams/36.png",
            },
            points: 35,
            goalsDiff: 4,
            group: "Premier League",
            form: "WDLLW",
            status: "same",
            description: null,
            all: {
              played: 23,
              win: 10,
              draw: 5,
              lose: 8,
              goals: { for: 34, against: 30 },
            },
            home: {
              played: 12,
              win: 6,
              draw: 3,
              lose: 3,
              goals: { for: 20, against: 16 },
            },
            away: {
              played: 11,
              win: 4,
              draw: 2,
              lose: 5,
              goals: { for: 14, against: 14 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 8,
            team: {
              id: 55,
              name: "Brentford",
              logo: "https://media-3.api-sports.io/football/teams/55.png",
            },
            points: 34,
            goalsDiff: 7,
            group: "Premier League",
            form: "DWDWW",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 8,
              draw: 10,
              lose: 4,
              goals: { for: 36, against: 29 },
            },
            home: {
              played: 11,
              win: 6,
              draw: 4,
              lose: 1,
              goals: { for: 23, against: 10 },
            },
            away: {
              played: 11,
              win: 2,
              draw: 6,
              lose: 3,
              goals: { for: 13, against: 19 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 9,
            team: {
              id: 49,
              name: "Chelsea",
              logo: "https://media-3.api-sports.io/football/teams/49.png",
            },
            points: 31,
            goalsDiff: 1,
            group: "Premier League",
            form: "DDDWL",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 8,
              draw: 7,
              lose: 7,
              goals: { for: 23, against: 22 },
            },
            home: {
              played: 10,
              win: 5,
              draw: 3,
              lose: 2,
              goals: { for: 13, against: 7 },
            },
            away: {
              played: 12,
              win: 3,
              draw: 4,
              lose: 5,
              goals: { for: 10, against: 15 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 10,
            team: {
              id: 40,
              name: "Liverpool",
              logo: "https://media.api-sports.io/football/teams/40.png",
            },
            points: 29,
            goalsDiff: 6,
            group: "Premier League",
            form: "LDLLW",
            status: "same",
            description: null,
            all: {
              played: 20,
              win: 8,
              draw: 5,
              lose: 7,
              goals: { for: 34, against: 28 },
            },
            home: {
              played: 10,
              win: 6,
              draw: 3,
              lose: 1,
              goals: { for: 23, against: 9 },
            },
            away: {
              played: 10,
              win: 2,
              draw: 2,
              lose: 6,
              goals: { for: 11, against: 19 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 11,
            team: {
              id: 66,
              name: "Aston Villa",
              logo: "https://media.api-sports.io/football/teams/66.png",
            },
            points: 28,
            goalsDiff: -6,
            group: "Premier League",
            form: "LWWDW",
            status: "same",
            description: null,
            all: {
              played: 21,
              win: 8,
              draw: 4,
              lose: 9,
              goals: { for: 25, against: 31 },
            },
            home: {
              played: 11,
              win: 5,
              draw: 2,
              lose: 4,
              goals: { for: 17, against: 15 },
            },
            away: {
              played: 10,
              win: 3,
              draw: 2,
              lose: 5,
              goals: { for: 8, against: 16 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 12,
            team: {
              id: 52,
              name: "Crystal Palace",
              logo: "https://media.api-sports.io/football/teams/52.png",
            },
            points: 25,
            goalsDiff: -10,
            group: "Premier League",
            form: "DLDDL",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 6,
              draw: 7,
              lose: 9,
              goals: { for: 20, against: 30 },
            },
            home: {
              played: 12,
              win: 4,
              draw: 4,
              lose: 4,
              goals: { for: 12, against: 17 },
            },
            away: {
              played: 10,
              win: 2,
              draw: 3,
              lose: 5,
              goals: { for: 8, against: 13 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 13,
            team: {
              id: 46,
              name: "Leicester",
              logo: "https://media-3.api-sports.io/football/teams/46.png",
            },
            points: 24,
            goalsDiff: -2,
            group: "Premier League",
            form: "WWDLL",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 7,
              draw: 3,
              lose: 12,
              goals: { for: 36, against: 38 },
            },
            home: {
              played: 11,
              win: 3,
              draw: 3,
              lose: 5,
              goals: { for: 15, against: 13 },
            },
            away: {
              played: 11,
              win: 4,
              draw: 0,
              lose: 7,
              goals: { for: 21, against: 25 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 14,
            team: {
              id: 65,
              name: "Nottingham Forest",
              logo: "https://media-3.api-sports.io/football/teams/65.png",
            },
            points: 24,
            goalsDiff: -20,
            group: "Premier League",
            form: "LWDWW",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 6,
              draw: 6,
              lose: 10,
              goals: { for: 17, against: 37 },
            },
            home: {
              played: 11,
              win: 5,
              draw: 3,
              lose: 3,
              goals: { for: 14, against: 12 },
            },
            away: {
              played: 11,
              win: 1,
              draw: 3,
              lose: 7,
              goals: { for: 3, against: 25 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 15,
            team: {
              id: 39,
              name: "Wolves",
              logo: "https://media.api-sports.io/football/teams/39.png",
            },
            points: 23,
            goalsDiff: -14,
            group: "Premier League",
            form: "WWLWD",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 6,
              draw: 5,
              lose: 11,
              goals: { for: 17, against: 31 },
            },
            home: {
              played: 11,
              win: 4,
              draw: 2,
              lose: 5,
              goals: { for: 9, against: 14 },
            },
            away: {
              played: 11,
              win: 2,
              draw: 3,
              lose: 6,
              goals: { for: 8, against: 17 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 16,
            team: {
              id: 48,
              name: "West Ham",
              logo: "https://media.api-sports.io/football/teams/48.png",
            },
            points: 20,
            goalsDiff: -8,
            group: "Premier League",
            form: "DDWLD",
            status: "same",
            description: null,
            all: {
              played: 22,
              win: 5,
              draw: 5,
              lose: 12,
              goals: { for: 19, against: 27 },
            },
            home: {
              played: 11,
              win: 4,
              draw: 2,
              lose: 5,
              goals: { for: 12, against: 13 },
            },
            away: {
              played: 11,
              win: 1,
              draw: 3,
              lose: 7,
              goals: { for: 7, against: 14 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 17,
            team: {
              id: 63,
              name: "Leeds",
              logo: "https://media-3.api-sports.io/football/teams/63.png",
            },
            points: 19,
            goalsDiff: -8,
            group: "Premier League",
            form: "DLDLD",
            status: "same",
            description: null,
            all: {
              played: 21,
              win: 4,
              draw: 7,
              lose: 10,
              goals: { for: 28, against: 36 },
            },
            home: {
              played: 10,
              win: 3,
              draw: 4,
              lose: 3,
              goals: { for: 15, against: 14 },
            },
            away: {
              played: 11,
              win: 1,
              draw: 3,
              lose: 7,
              goals: { for: 13, against: 22 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 18,
            team: {
              id: 45,
              name: "Everton",
              logo: "https://media.api-sports.io/football/teams/45.png",
            },
            points: 18,
            goalsDiff: -12,
            group: "Premier League",
            form: "WLLLD",
            status: "same",
            description: "Relegation - Championship",
            all: {
              played: 21,
              win: 4,
              draw: 6,
              lose: 11,
              goals: { for: 16, against: 28 },
            },
            home: {
              played: 11,
              win: 3,
              draw: 2,
              lose: 6,
              goals: { for: 10, against: 14 },
            },
            away: {
              played: 10,
              win: 1,
              draw: 4,
              lose: 5,
              goals: { for: 6, against: 14 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 19,
            team: {
              id: 35,
              name: "Bournemouth",
              logo: "https://media-3.api-sports.io/football/teams/35.png",
            },
            points: 18,
            goalsDiff: -24,
            group: "Premier League",
            form: "DLDLL",
            status: "same",
            description: "Relegation - Championship",
            all: {
              played: 22,
              win: 4,
              draw: 6,
              lose: 12,
              goals: { for: 20, against: 44 },
            },
            home: {
              played: 11,
              win: 3,
              draw: 4,
              lose: 4,
              goals: { for: 11, against: 12 },
            },
            away: {
              played: 11,
              win: 1,
              draw: 2,
              lose: 8,
              goals: { for: 9, against: 32 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
          {
            rank: 20,
            team: {
              id: 41,
              name: "Southampton",
              logo: "https://media-3.api-sports.io/football/teams/41.png",
            },
            points: 15,
            goalsDiff: -22,
            group: "Premier League",
            form: "LLLWL",
            status: "same",
            description: "Relegation - Championship",
            all: {
              played: 22,
              win: 4,
              draw: 3,
              lose: 15,
              goals: { for: 18, against: 40 },
            },
            home: {
              played: 11,
              win: 1,
              draw: 3,
              lose: 7,
              goals: { for: 10, against: 19 },
            },
            away: {
              played: 11,
              win: 3,
              draw: 0,
              lose: 8,
              goals: { for: 8, against: 21 },
            },
            update: "2023-02-12T00:00:00+00:00",
          },
        ],
      ],
    },
  },
];
